services:
  postgres:
    image: postgres:13
    ports:
      - "1000:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: compensationManagerDB
    volumes:
      - volCompensationManagerDB:/var/lib/postgresql/data
    restart: always

volumes:
  volCompensationManagerDB:


