version: "3"

services:
  ml-storitev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    environment:
      - PROJECT=perko.domen/fraud-detection
      - API_TOKEN=eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiJjYjFiOWYwYi0xMzkyLTQ3Y2ItYmRhZi1mM2MxMjlmNGVjZmYifQ==
      - MODEL=FRAUD-MLP
      - STAGE=production