services:
  postgres:
    image: postgres:13
    ports:
      - "3001:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: insuranceDB
    volumes:
      - volInsuranceDB:/var/lib/postgresql/data
    restart: always


volumes:
  volInsuranceDB: